# permissions for end users to view darkrooms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: darkroom-viewer-role
rules:
- apiGroups:
  - deployments.example.com
  resources:
  - darkrooms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deployments.example.com
  resources:
  - darkrooms/status
  verbs:
  - get
