# permissions for end users to edit darkrooms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: darkroom-editor-role
rules:
- apiGroups:
  - deployments.example.com
  resources:
  - darkrooms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.example.com
  resources:
  - darkrooms/status
  verbs:
  - get
