apiVersion: deployments.example.com/v1alpha1
kind: Darkroom
metadata:
  name: darkroom-sample
spec:
  source:
    baseUrl: https://ajatprabha.in/assets
    type: WebFolder
  subDomains:
    - ajatprabha
  version: 0.1.0
